#NAME: Adam Cole
#EMAIL: ############@gmail.com
#ID: #########

CC = gcc
CFLAGS = -Wall -Wextra -g
files = git.png my_beaglebone.jpg connected.png copy.png build_run.png Makefile README

.SILENT:

clean:
	rm -f *.o *.txt *.tar.gz lab1b-client lab1b-server
dist:
	tar -czvf lab4a-#########.tar.gz $(files)
