#NAME: Adam Cole
#EMAIL: adam.cole5621@gmail.com
#ID: 004912373

CC = gcc
CFLAGS = -Wall -Wextra -g
files = git.png my_beaglebone.jpg connected.png copy.png build_run.png Makefile README

.SILENT:

clean:
	rm -f *.o *.txt *.tar.gz lab1b-client lab1b-server
dist:
	tar -czvf lab4a-004912373.tar.gz $(files)
