#NAME: Adam Cole
#EMAIL: #############@gmail.com
#ID: #########

CC = gcc
CFLAGS = -Wall -Wextra -g
files = lab1a.c Makefile README

.SILENT:

all:
	$(CC) $(CFLAGS) -o lab1a lab1a.c
clean:
	rm -f *.o *.txt *.tar.gz lab1a
dist:
	tar -czvf lab1a-#########.tar.gz $(files)
